version: '3'

services:
  consul:
    command: -server  -h ip-172-31-19-131 -bootstrap-expect 3  -advertise 52.57.99.89 -retry-join 52.48.82.32 -retry-join 35.197.251.183
    image: progrium/consul:latest
    container_name: consul
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8500:8600"
      - "8301:8301/udp"
      - "8302:8302/udp"
    environment:
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
    network_mode: host
    restart: always


  consul-agent:
    command: consul agent   -data-dir /tmp -advertise 172.31.22.85 -bind 172.31.22.85 -client 172.31.22.85 &
    image: progrium/consul:latest
    container_name: consul-agent
    ports:
       - "8300:8300"
       - "8400:8400"
       - "8500:8500"
       - "8600:8600"
       - "8301:8301/udp"
       - "8302:8302/udp"
    environment:
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
      CONSUL_CLIENT_INTERFACE: eth0
      CONSUL_BIND_INTERFACE: eth0
    network_mode: host
    restart: always
    depends_on:
       - consul

  registrator:
    command:   consul://consul-agent:8500
    image: gliderlabs/registrator:latest
    links:
      - consul-agent
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    restart: always
    depends_on:
      - consul-agent

#  lb1:
#    build: ./lb_org
#    ports:
#      - "443:443"
#    environment:
#      CONSUL_URL: consul:8500
#      restart: always
#      hostname: lb1
#      domainname: monifair.com
      #extra_hosts:
      #  - "${DNSDOMAIN}:${DNSDOMAINIP}"

#  elk1:
#    build: ./elk
#    ports:
#      - "5601:5601"
#      - "9200:9200"
#      - "5000:5000"
#      - "5044:5044"
#    restart: always
