version: '3'

services:
  consul:
    command: -server -advertise 52.57.99.89 -bootstrap-expect 3     -retry-join 52.48.82.32 -retry-join 35.197.251.183
    image: progrium/consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8500:8600"
      - "8301:8301/udp"
      - "8302:8302/udp"
    environment:
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
    network_mode: host
    restart: always


  consul-agent1:
   command: consul agent   -data-dir /tmp  -bind=52.57.99.89  -client=52.57.99.89
   image: progrium/consul:latest
   environment:
     CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
   network_mode: host
   restart: always
   depends_on:
     - consul

  registrator1:
    command:  -ip=52.57.99.89 consul://consul-agent1:8500
    image: gliderlabs/registrator:latest
    links:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    restart: always
    depends_on:
      - consul-agent1

  lb1:
    build: ./lb_org
    ports:
      - "443:443"
    environment:
      CONSUL_URL: consul:8500
      restart: always
      hostname: lb1
      domainname: monifair.com
      #extra_hosts:
      #  - "${DNSDOMAIN}:${DNSDOMAINIP}"

  elk1:
    build: ./elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5000:5000"
      - "5044:5044"
    restart: always
