version: '3'

services:
  consul2:
  command: -server  -bootstrap-expect=3  -advertise 35.157.253.101
  image: consul:latest
  ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:8600"
    - "8301/udp:8301/udp"
    - "8302/udp:8302/udp"
  environment:
    CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
  network_mode: host
  restart: always

registrator2:
  command:  -ip= 35.157.253.101 consul://consul2:8500
  image: gliderlabs/registrator:latest
  links:
    - consul2
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  network_mode: host
  restart: always
  depends_on:
    - consul2

consul_notifier2:
  image: aisaac/swarm-consul-notifier
  container_name: consul_notifier2
  network_mode: host
  environment:
    CONSUL_ADDR: 35.157.253.101
    #CONSUL_SERVICE_PORT: 8500
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  restart: always
  depends_on:
    - consul2
