version: '3'

services:
   consul:
     command: -server  -bootstrap-expect 3   -data-dir /tmp  -advertise 52.48.82.32  -retry-join 52.57.99.89 -retry-join 35.197.251.183
     image: progrium/consul:latest
     ports:
       - "8300"
       - "8400"
       - "8500"
       - "8600"
       - "8313:8301/udp"
       - "8314:8302/udp"
     environment:
       CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
     network_mode: host
     restart: always

  consul-agent2:
    command: consul agent   -data-dir /tmp  -bind=52.48.82.32  -client=52.48.82.32
    image: progrium/consul:latest
    environment:
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
    network_mode: host
    restart: always
    depends_on:
      - consul


   registrator2:
     command:  -ip= 52.48.82.32 consul://consul-agent2:8500
     image: gliderlabs/registrator:latest
     links:
       - consul
     volumes:
       - "/var/run/docker.sock:/tmp/docker.sock"
     restart: always
     depends_on:
       - consul-agent2

   lb2:
     build: ./lb_org
     ports:
       - "443:443"
     environment:
       CONSUL_URL: consul:8500
     restart: always
     hostname: lb2
     domainname: monifair.com
     #extra_hosts:
      # - "${DNSDOMAIN}:${DNSDOMAINIP}"

   elk2:
     build: ./elk
     ports:
       - "5601:5601"
       - "9200:9200"
       - "5000:5000"
       - "5044:5044"
     restart: always
